name: chord_transposer
description: A Dart package for transposing chords into any given key.
version: 0.0.1
homepage: https://github.com/JakesMD/chord_transposer

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
